### ISSUE TITLE
Continuous collection of tweets: restart if program stops

### ISSUE THREAD

**Issue by christopherkullenberg** [computermacgyver/twitter-python#2]
First I want to say big thanks for a great piece of software!

I use Twitter-python to record tweets on a day-to-day basis, storing the json files for future analysis and converting it automatically to csv and then to gexf. It works great. 

However, once a week or so I have to manually restart `nohup python streaming.py >> logfile 2>> errorfile` because it exited withoul printing any errors. 

What would be the best way of keeping it running and, if needed, restarting it. 

I run twitter-python in a screen on ubuntu linux.

**Comment by computermacgyver** [comment]
Thanks for reporting this. I've updated the code with one more block of exception handling in streaming.py . This should hopefully fix the errors you're having: I've found that often there are small http/Twitter errors that were not otherwise handled before.

At the bottom of the streaming.py file there is a place you could put in your email address and SMTP server to get email alters, but it is not necessary to do so.

The error information for your previous runs should be in the file called 'errorfile' this is what the `2>>errorfile` part of the command is doing (redirecting standard error to the file with name errorfile). If you run the script inside a screen session, you will not need to include nohup and can choose not to redirect output (i.e., you can just run `python streaming.py` in screen if you'd like).

Cheers,
Scott

**Comment by christopherkullenberg** [comment]
Thanks a lot Scott! I will update. Also, thanks for responding so quickly. This will work excellent with my current research. Will make sure to cite if I publish my findings

**Comment by computermacgyver** [comment]
No problem: I'm glad to have been able to help. Thank you for uncovering this issue and bringing it to my attention. Do let me know if anything else seems amiss.
