### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by guinslym** [computermacgyver/twitter-python#3]
Hi @computermacgyver !

There is nothing to fix on your github repo but on the steaming.py I would like to know why do we have to wait 30 min before reconnecting to Twitter. I.e a [TwitterConnectionError](https://dev.twitter.com/overview/api/response-codes) (status code 500)

```
#streaming.py line 145
time.sleep(1800)#Sleep thirty minutes and resume 
```

My question or issue is not a bug is more about the "historical conception". I would like to know if previously when Twitter had a ConnectionError if you had to wait at least 30min. before everything get fixed.

**Comment by computermacgyver** [comment]
Hi @guinslym . As far as I recall, 30 minutes was not an official Twitter figure. I believe there was a more complicated backoff strategy that was published earlier and rather than implement that strategy I just added a 30 minute wait as a quick/easy solution (certainly not the best choice, but it wasn't an error message that occurred much at the time I wrote the code). 

The current documentation just advises

```
Twitter does not make public the number of connection attempts which will cause a rate limiting to 
occur, but there is some tolerance for testing and development. A few dozen connection attempts  
from time to time will not trigger a limit. However, it is essential to stop further connection attempts 
for a few minutes if a HTTP 420 response is received. If your client is rate limited frequently, it is 
possible that your IP will be blocked from accessing Twitter for an indeterminate period of time.
```
